steps:
  - id: 'build'
    name: 'gcr.io/cloud-builders/go'
    env: ['PROJECT_ROOT=drone-gcloud-helm']
    args: ['install', '.']

  - id: 'image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/drone-gcloud-helm:$SHORT_SHA', '.']

images: ['gcr.io/$PROJECT_ID/drone-gcloud-helm:$SHORT_SHA']
tags:
  - 'latest'
